apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-api
          image: sahiljgupta/04-eks-kub-deploy-starting-setup:users-api-v1
          env:
            - name: MONGODB_CONNECTION_URI
              value: 'mongodb://max:secret@xxxxxxxxxxxxxxxazonaws.com:27017/users?authSource=admin'
            - name: AUTH_API_ADDRESSS
              value: 'auth-service.default:3000'



